// ReactWithForm/src/components/CreatePersonModal.jsx
import React, { useState } from 'react';
import { useCreatePerson } from '../hooks/useCreatePerson';
import { PersonForm } from './Form';
export const CreatePersonModal = ({ show, onClose }) => {
  const { createPerson, isLoading, error: apiError } = useCreatePerson();
  const [formData, setFormData] = useState({
    genero: 'Masculino',
    ciudad: 'Milagro',
  });

  if (!show) return null;

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await createPerson(formData);
      onClose();
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <div className="modal">
      <div className="modal-content">
        <h2>Crear Nueva Persona</h2>
        <form onSubmit={handleSubmit}>
          <PersonForm formData={formData} handleChange={handleChange} />
          
          <br />
          <button type="submit" disabled={isLoading}>
            {isLoading ? 'Creando...' : 'Crear Persona'}
          </button>
          <button type="button" onClick={onClose} className='button-danger' >Cancelar</button>
        </form>
        {apiError && <p style={{ color: 'red' }}>{apiError}</p>}
      </div>
    </div>
  );
};

// VueWithForm/src/components/CreatePersonModal.vue
<template>
    <div v-if="show" class="modal">
        <div class="modal-content">
        <h2>Crear Nueva Persona</h2>
        <PersonForm
            v-model:formData="formData"
            :errors="errors"
        />
        <div class="button-group">
            <button @click="handleSubmit" :disabled="creating">
            {{ creating ? 'Creando...' : 'Crear Persona' }}
            </button>
            <button @click="onClose" class="button-danger">Cancelar</button>
        </div>
        <p v-if="error" class="error-message">{{ error }}</p>
        </div>
    </div>
</template>

<script setup>
import { ref } from 'vue';
import PersonForm from './PersonForm.vue';
import { useCreatePerson } from '../composables/usePersons';

const props = defineProps({
    show: Boolean,
    onClose: Function
});

const emit = defineEmits(['personCreated']);
const { createPerson, creating, error: apiError } = useCreatePerson();
const formData = ref({
    genero: 'Masculino',
    ciudad: 'Milagro'
});
const errors = ref({});
const error = ref(null);

const handleSubmit = async () => {
    errors.value = {};
    error.value = null;
    
    try {
        await createPerson(formData.value);
        emit('personCreated');
        props.onClose();
        formData.value = {
            genero: 'Masculino',
            ciudad: 'Milagro'
        };
    } catch (err) {
        // errores de validación específicos
        if (err.errors) {
            errors.value = err.errors;
        }
        // mensaje específico 
        else if (err.message) {
            if (err.message.toLowerCase().includes('dni')) {
                errors.value = {
                    dni: { message: err.message }
                };
            } else {
                error.value = err.message;
            }
        }
        // Cualquier otro tipo de error
        else {
            error.value = 'Error al crear la persona';
        }
    }
};
</script>

<style scoped>
.button-group {
    display: flex;
    gap: 10px;
    justify-content: flex-end;
    margin-top: 20px;
}
</style>
