// ReactWithForm/src/components/DeletePersonModal.jsx
import { useDeletePerson } from '../hooks/useDeletePerson';

export const DeletePersonModal = ({ show, onClose, personId }) => {
  const { removePerson, isLoading, error: apiError } = useDeletePerson();

  if (!show) return null;

  const handleDelete = async () => {
    try {
      await removePerson(personId);
      onClose();
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <div className="modal">
      <div className="modal-content">
        <h2>Confirmar Eliminación</h2>
        <p>¿Estás seguro de que deseas eliminar a esta persona?</p>
        
        {apiError && <p style={{ color: 'red' }}>{apiError}</p>}
        
        <button onClick={handleDelete} disabled={isLoading}>
          {isLoading ? 'Eliminando...' : 'Si'}
        </button>
        <button onClick={onClose} disabled={isLoading} className="button-danger">
          Cancelar
        </button>
      </div>
    </div>
  );
};

// VueWithForm/src/components/DeletePersonModal.vue
<template>
    <div v-if="show" class="modal">
        <div class="modal-content">
        <h2>Confirmar Eliminación</h2>
        <p>¿Estás seguro de que deseas eliminar a esta persona?</p>
        <div class="button-group">
            <button @click="handleDelete" :disabled="deleting">
            {{ deleting ? 'Eliminando...' : 'Si' }}
            </button>
            <button @click="onClose" :disabled="deleting" class="button-danger">
            Cancelar
            </button>
        </div>

        <p v-if="error" class="error-message">{{ error }}</p>
        </div>
    </div>
</template>

<script setup>
import { ref } from 'vue';
import { useDeletePerson } from '../composables/usePersons';

const props = defineProps({
    show: Boolean,
    onClose: Function,
    personId: String
});

const emit = defineEmits(['personDeleted']);
const { deletePerson, deleting } = useDeletePerson();
const error = ref(null);

const handleDelete = async () => {
    error.value = null;
    try {
        if (!props.personId) {
        error.value = 'No se puede eliminar: ID no proporcionado';
        return;
        }
        await deletePerson(props.personId);
        emit('personDeleted');
        props.onClose();
    } catch (err) {
        error.value = err.message;
        console.error('Error al eliminar:', err);
    }
    };
</script>

<style scoped>
    .button-group {
    display: flex;
    gap: 10px;
    justify-content: flex-end;
    margin-top: 20px;
    }

    .error-message {
    color: #e04e6b;
    text-align: center;
    margin-top: 1rem;
    }

    .button-danger {
    background-color: #e04e6b;
    color: white;
    border: none;
    padding: 0.5rem 1rem;
    cursor: pointer;
    }
</style>
