// ReactWithForm/src/components/UpdatePersonModal.jsx
import React, { useState, useEffect } from 'react';
import { useUpdatePerson } from '../hooks/useUpdatePerson';
import { PersonForm } from './Form';

export const UpdatePersonModal = ({ show, onClose, person }) => {
  const { updatePerson, isLoading, error: apiError } = useUpdatePerson();
  const [formData, setFormData] = useState({});

  useEffect(() => {
    if (person) {
      const formattedDate = person.fechaNacimiento ? person.fechaNacimiento.split('T')[0] : '';
      setFormData({ ...person, fechaNacimiento: formattedDate });
    }
  }, [person]);

  if (!show) return null;

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await updatePerson(person._id, formData);
      onClose();
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <div className="modal">
      <div className="modal-content">
        <h2>Editar Persona</h2>
        <form onSubmit={handleSubmit}>
          <PersonForm formData={formData} handleChange={handleChange} />          
          <br />
          <button type="submit" disabled={isLoading}>
            {isLoading ? 'Actualizando...' : 'Actualizar'}
          </button>
          <button type="button" onClick={onClose} className='button-danger' >Cancelar</button>
        </form>
        {apiError && <p style={{ color: 'red' }}>{apiError}</p>}
      </div>
    </div>
  );
};

// VueWithForm/src/components/UpdatePersonModal.vue
<template>
    <div v-if="show" class="modal">
        <div class="modal-content">
        <h2>Editar Persona</h2>
        <PersonForm
            v-model:formData="localFormData"
            :errors="errors"
        />
        <div class="button-group">
            <button @click="handleSubmit" :disabled="updating">
            {{ updating ? 'Actualizando...' : 'Actualizar' }}
            </button>
            <button @click="onClose" class="button-danger">Cancelar</button>
        </div>
        <p v-if="error" class="error-message">{{ error }}</p>
        </div>
    </div>
</template>

<script setup>
import { ref, watch } from 'vue';
import PersonForm from './PersonForm.vue';
import { useUpdatePerson } from '../composables/usePersons';

const props = defineProps({
    show: Boolean,
    onClose: Function,
    person: Object
});

const emit = defineEmits(['personUpdated']);
const { updatePerson, updating, error: apiError } = useUpdatePerson();
const localFormData = ref({});
const errors = ref({});
const error = ref(null);

watch(() => props.person, (newPerson) => {
    if (newPerson) {
        const formattedDate = newPerson.fechaNacimiento ? newPerson.fechaNacimiento.split('T')[0] : '';
        localFormData.value = { ...newPerson, fechaNacimiento: formattedDate };
        errors.value = {};
        error.value = null;
    }
}, { immediate: true });

const handleSubmit = async () => {
    errors.value = {};
    error.value = null;
    
    try {
        await updatePerson(props.person._id, localFormData.value);
        emit('personUpdated');
        props.onClose();
    } catch (err) {
        if (err.response?.data?.errors) {
        errors.value = err.response.data.errors;
        } else {
        error.value = err.response?.data?.message || 'Error al actualizar la persona';
        }
    }
};
</script>
